version: "3"

volumes:
  esdata:
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch

    logging:
      driver: none
    restart: "on_failure"

    ports:
      - 9300:9300
      - 9200:9200
